# Generated by Django 3.2.18 on 2023-06-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('package_name', models.CharField(blank=True, default=None, max_length=200)),
                ('price', models.CharField(blank=True, default=None, max_length=200)),
                ('promotion', models.CharField(blank=True, default=None, max_length=200)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
