# Generated by Django 3.2.18 on 2023-05-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200)),
                ('alias', models.CharField(blank=True, default=None, max_length=200)),
                ('is_offical', models.BooleanField(blank=True, default=True)),
                ('user_name', models.CharField(blank=True, default=None, max_length=100)),
                ('artist_names', models.CharField(blank=True, default=None, max_length=100)),
                ('is_world_wide', models.BooleanField(blank=True, default=True)),
                ('thumbnail_m', models.CharField(blank=True, default=None, max_length=400)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400)),
                ('duration', models.IntegerField(blank=True, default=None)),
                ('zing_choice', models.BooleanField(blank=True, default=False)),
                ('is_private', models.BooleanField(blank=True, default=False)),
                ('pre_release', models.BooleanField(blank=True, default=False)),
                ('release_date', models.IntegerField(blank=True, default=None)),
                ('is_indie', models.BooleanField(blank=True, default=False)),
                ('streaming_status', models.IntegerField(blank=True, default=1)),
                ('allow_audio_ads', models.BooleanField(blank=True, default=True)),
                ('has_lyric', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongOfPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlists')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.songs')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongOfAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.songs')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
