# Generated by Django 3.2.18 on 2023-06-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_songs_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingUrlSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quality_128', models.TextField(blank=True, default=None)),
                ('quality_320', models.TextField(blank=True, default=None)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.songs')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
