# Generated by Django 3.2.18 on 2023-06-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStreamingUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quality_480', models.CharField(blank=True, default=None, max_length=400)),
                ('quality_720', models.CharField(blank=True, default=None, max_length=400)),
                ('quality_1080', models.CharField(blank=True, default=None, max_length=400)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videos')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoRecommendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.videos')),
                ('video_recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_recommend', to='video.videos')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
