# Generated by Django 3.2.18 on 2023-04-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=300)),
                ('is_offical', models.BooleanField(blank=True, default=True)),
                ('is_indie', models.BooleanField(blank=True, default=False)),
                ('release_date', models.CharField(blank=True, default=None, max_length=100)),
                ('sort_description', models.TextField(blank=True, default=None)),
                ('released_at', models.IntegerField(blank=True, default=None)),
                ('pr', models.BooleanField(blank=True, default=False)),
                ('artist_names', models.CharField(blank=True, default=None, max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumOfTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.topicalbum')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
