# Generated by Django 3.2.18 on 2023-04-23 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('spotlight', models.BooleanField(default=False)),
                ('alias', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('thumbnail_m', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('is_oa', models.BooleanField(default=True)),
                ('is_oa_brand', models.BooleanField(default=False)),
                ('total_follow', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistOfPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artists')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlists')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
