# Generated by Django 3.2.18 on 2023-05-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        ('artists', '0003_artistofsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistofsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.songs'),
        ),
    ]
