# Generated by Django 3.2.18 on 2023-05-23 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0002_topicplaylistofhub'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='follow',
            field=models.ManyToManyField(related_name='follow_playlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
