# Generated by Django 3.2.18 on 2023-07-07 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0005_alter_playlists_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='create_by_user',
            field=models.ManyToManyField(related_name='create_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
