# Generated by Django 3.2.18 on 2023-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_playlists_create_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='thumbnail',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
