# Generated by Django 3.2.18 on 2023-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_authuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
