# Generated by Django 3.2.18 on 2023-05-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcast_podcastoftopic_topicpodcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodCastOfPodCastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcast')),
                ('podcast_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcastcategory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
