# Generated by Django 3.2.18 on 2023-05-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_podcastofpodcastcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200)),
                ('description', models.TextField(blank=True, default=None)),
                ('duration', models.IntegerField(blank=True, default=None)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400)),
                ('thumbnail_m', models.CharField(blank=True, default=None, max_length=400)),
                ('release_date', models.IntegerField(blank=True, default=None)),
                ('content_type', models.CharField(blank=True, default='episode', max_length=100)),
                ('episode', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisodeOfPodCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcast')),
                ('podcast_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcastepisode')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
