# Generated by Django 3.2.18 on 2023-05-23 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0004_podcastepisode_podcastepisodeofpodcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='follow',
            field=models.ManyToManyField(related_name='follow_episode_podcast', to=settings.AUTH_USER_MODEL),
        ),
    ]
