# Generated by Django 3.2.18 on 2023-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_podcastepisode_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='type',
            field=models.CharField(blank=True, default='song', max_length=100),
        ),
    ]
