# Generated by Django 3.2.18 on 2023-06-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_alter_podcastepisode_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastStreamingUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quality_64', models.CharField(blank=True, default=None, max_length=400)),
                ('quality_128', models.CharField(blank=True, default=None, max_length=400)),
                ('quality_320', models.CharField(blank=True, default=None, max_length=400)),
                ('podcast_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcastepisode')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
